-- AltArmy TBC — WoW Forever's Waylaid Crates and the bundles that fill them (Economy tab).
-- GENERATED by scripts/generate-waylaid-crates.py from the client's game data: do not edit by hand.
-- A shipment takes any ONE of its bundles. `kind`: Gathered (raw goods) or Crafted (crafted goods).
-- The unread "Waylaid Crate" (GENERIC) becomes a random shipment when its label is read.
-- ITEMS: every item the bundles' crafting trees touch (`vendor` copper per `per` units where a vendor
-- sells it; `bop` binds on pickup). RECIPES: the craft recipes by spell id (`out`, `n` made per cast,
-- `prof`, `reagents`), as in Writs.lua.

if not AltArmy then return end

AltArmy.WaylaidCrates = AltArmy.WaylaidCrates or {}
local C = AltArmy.WaylaidCrates

C.GENERIC = 248549
C.TIERS = { "Apprentice", "Journeyman", "Expert", "Artisan" }
C.LIST = {
    { id = 248549, name = "Waylaid Crate", short = "Waylaid Crate (unread)", random = true, bundles = {} },
    { id = 248682, name = "Waylaid Crate: Apprentice Herbs", short = "Apprentice Herbs",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2447, count = 20, name = "Peacebloom" },
        { item = 765, count = 20, name = "Silverleaf" },
        { item = 2449, count = 10, name = "Earthroot" },
        { item = 785, count = 10, name = "Mageroyal" },
        { item = 2450, count = 10, name = "Briarthorn" },
    } },
    { id = 248683, name = "Waylaid Crate: Apprentice Ore", short = "Apprentice Ore",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2770, count = 20, name = "Copper Ore" },
        { item = 2771, count = 20, name = "Tin Ore" },
    } },
    { id = 248684, name = "Waylaid Crate: Apprentice Textiles", short = "Apprentice Textiles",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 2589, count = 40, name = "Linen Cloth" },
        { item = 2318, count = 20, name = "Light Leather" },
    } },
    { id = 248685, name = "Waylaid Crate: Apprentice Curiosities", short = "Apprentice Curiosities",
      tier = "Apprentice", kind = "Gathered", bundles = {
        { item = 10940, count = 20, name = "Strange Dust" },
        { item = 10939, count = 4, name = "Greater Magic Essence" },
        { item = 10978, count = 6, name = "Small Glimmering Shard" },
        { item = 11084, count = 2, name = "Large Glimmering Shard" },
    } },
    { id = 248686, name = "Waylaid Crate: Journeyman Herbs", short = "Journeyman Herbs",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 3820, count = 10, name = "Stranglekelp" },
        { item = 2453, count = 10, name = "Bruiseweed" },
        { item = 3355, count = 10, name = "Wild Steelbloom" },
        { item = 3369, count = 10, name = "Grave Moss" },
        { item = 3356, count = 10, name = "Kingsblood" },
    } },
    { id = 248687, name = "Waylaid Crate: Journeyman Ore", short = "Journeyman Ore",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 2775, count = 10, name = "Silver Ore" },
        { item = 2772, count = 20, name = "Iron Ore" },
    } },
    { id = 248688, name = "Waylaid Crate: Journeyman Textiles", short = "Journeyman Textiles",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 2592, count = 20, name = "Wool Cloth" },
        { item = 4306, count = 40, name = "Silk Cloth" },
        { item = 2319, count = 20, name = "Medium Leather" },
    } },
    { id = 248689, name = "Waylaid Crate: Journeyman Curiosities", short = "Journeyman Curiosities",
      tier = "Journeyman", kind = "Gathered", bundles = {
        { item = 11083, count = 20, name = "Soul Dust" },
        { item = 11082, count = 4, name = "Greater Astral Essence" },
        { item = 11138, count = 6, name = "Small Glowing Shard" },
        { item = 11139, count = 2, name = "Large Glowing Shard" },
    } },
    { id = 248690, name = "Waylaid Crate: Earthly Expert Herbs", short = "Earthly Expert Herbs",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 3357, count = 20, name = "Liferoot" },
        { item = 3818, count = 10, name = "Fadeleaf" },
        { item = 3821, count = 10, name = "Goldthorn" },
        { item = 3358, count = 10, name = "Khadgar's Whisker" },
    } },
    { id = 248691, name = "Waylaid Crate: Flowering Expert Herbs", short = "Flowering Expert Herbs",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 3819, count = 10, name = "Wintersbite" },
        { item = 4625, count = 10, name = "Firebloom" },
        { item = 8831, count = 20, name = "Purple Lotus" },
        { item = 8836, count = 10, name = "Arthas' Tears" },
    } },
    { id = 248692, name = "Waylaid Crate: Expert Ore", short = "Expert Ore",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 2776, count = 10, name = "Gold Ore" },
        { item = 3858, count = 20, name = "Mithril Ore" },
    } },
    { id = 248693, name = "Waylaid Crate: Expert Textiles", short = "Expert Textiles",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 4338, count = 40, name = "Mageweave Cloth" },
        { item = 4234, count = 20, name = "Heavy Leather" },
    } },
    { id = 248694, name = "Waylaid Crate: Expert Curiosities", short = "Expert Curiosities",
      tier = "Expert", kind = "Gathered", bundles = {
        { item = 11137, count = 20, name = "Vision Dust" },
        { item = 11135, count = 4, name = "Greater Mystic Essence" },
        { item = 11177, count = 6, name = "Small Radiant Shard" },
        { item = 11178, count = 2, name = "Large Radiant Shard" },
    } },
    { id = 248695, name = "Waylaid Crate: Earthly Artisan Herbs", short = "Earthly Artisan Herbs",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 13464, count = 10, name = "Golden Sansam" },
        { item = 8838, count = 20, name = "Sungrass" },
        { item = 8839, count = 10, name = "Blindweed" },
        { item = 8845, count = 10, name = "Ghost Mushroom" },
        { item = 8846, count = 10, name = "Gromsblood" },
    } },
    { id = 248696, name = "Waylaid Crate: Flowering Artisan Herbs", short = "Flowering Artisan Herbs",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 13463, count = 20, name = "Dreamfoil" },
        { item = 13465, count = 20, name = "Mountain Silversage" },
        { item = 13466, count = 20, name = "Plaguebloom" },
        { item = 13467, count = 20, name = "Icecap" },
    } },
    { id = 248697, name = "Waylaid Crate: Artisan Ore", short = "Artisan Ore",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 7911, count = 10, name = "Truesilver Ore" },
        { item = 10620, count = 20, name = "Thorium Ore" },
        { item = 11370, count = 20, name = "Dark Iron Ore" },
    } },
    { id = 248698, name = "Waylaid Crate: Artisan Textiles", short = "Artisan Textiles",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 14047, count = 40, name = "Runecloth" },
        { item = 4304, count = 20, name = "Thick Leather" },
        { item = 8170, count = 20, name = "Rugged Leather" },
    } },
    { id = 248699, name = "Waylaid Crate: Artisan Curiosities", short = "Artisan Curiosities",
      tier = "Artisan", kind = "Gathered", bundles = {
        { item = 11176, count = 20, name = "Dream Dust" },
        { item = 11175, count = 4, name = "Greater Nether Essence" },
        { item = 14343, count = 6, name = "Small Brilliant Shard" },
        { item = 14344, count = 2, name = "Large Brilliant Shard" },
    } },
    { id = 248702, name = "Waylaid Crate: Apprentice Fabrics", short = "Apprentice Fabrics",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 4231, count = 2, name = "Cured Light Hide" },
        { item = 2996, count = 20, name = "Bolt of Linen Cloth" },
    } },
    { id = 248703, name = "Waylaid Crate: Apprentice Ingots", short = "Apprentice Ingots",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 2840, count = 20, name = "Copper Bar" },
        { item = 3576, count = 20, name = "Tin Bar" },
        { item = 2841, count = 10, name = "Bronze Bar" },
    } },
    { id = 248704, name = "Waylaid Crate: Apprentice Parts", short = "Apprentice Parts",
      tier = "Apprentice", kind = "Crafted", bundles = {
        { item = 4359, count = 16, name = "Handful of Copper Bolts" },
        { item = 4361, count = 16, name = "Copper Tube" },
        { item = 4363, count = 4, name = "Copper Modulator" },
    } },
    { id = 248705, name = "Waylaid Crate: Journeyman Fabrics", short = "Journeyman Fabrics",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 2997, count = 6, name = "Bolt of Woolen Cloth" },
        { item = 4305, count = 10, name = "Bolt of Silk Cloth" },
        { item = 4233, count = 2, name = "Cured Medium Hide" },
    } },
    { id = 248706, name = "Waylaid Crate: Journeyman Ingots", short = "Journeyman Ingots",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 2842, count = 10, name = "Silver Bar" },
        { item = 3575, count = 20, name = "Iron Bar" },
    } },
    { id = 248707, name = "Waylaid Crate: Journeyman Parts", short = "Journeyman Parts",
      tier = "Journeyman", kind = "Crafted", bundles = {
        { item = 4371, count = 8, name = "Bronze Tube" },
        { item = 4375, count = 7, name = "Whirring Bronze Gizmo" },
        { item = 4382, count = 4, name = "Bronze Framework" },
        { item = 10558, count = 45, name = "Gold Power Core" },
    } },
    { id = 248708, name = "Waylaid Crate: Expert Fabrics", short = "Expert Fabrics",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 4339, count = 8, name = "Bolt of Mageweave" },
        { item = 4236, count = 2, name = "Cured Heavy Hide" },
    } },
    { id = 248709, name = "Waylaid Crate: Expert Ingots", short = "Expert Ingots",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 3860, count = 20, name = "Mithril Bar" },
        { item = 3859, count = 15, name = "Steel Bar" },
        { item = 3577, count = 10, name = "Gold Bar" },
    } },
    { id = 248710, name = "Waylaid Crate: Expert Parts", short = "Expert Parts",
      tier = "Expert", kind = "Crafted", bundles = {
        { item = 4387, count = 8, name = "Iron Strut" },
        { item = 10559, count = 5, name = "Mithril Tube" },
        { item = 10560, count = 12, name = "Unstable Trigger" },
        { item = 10561, count = 5, name = "Mithril Casing" },
    } },
    { id = 248711, name = "Waylaid Crate: Artisan Fabrics", short = "Artisan Fabrics",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 14048, count = 8, name = "Bolt of Runecloth" },
        { item = 8172, count = 2, name = "Cured Thick Hide" },
    } },
    { id = 248712, name = "Waylaid Crate: Artisan Ingots", short = "Artisan Ingots",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 11371, count = 2, name = "Dark Iron Bar" },
        { item = 6037, count = 10, name = "Truesilver Bar" },
        { item = 12359, count = 20, name = "Thorium Bar" },
    } },
    { id = 248713, name = "Waylaid Crate: Artisan Parts", short = "Artisan Parts",
      tier = "Artisan", kind = "Crafted", bundles = {
        { item = 15994, count = 5, name = "Thorium Widget" },
        { item = 18631, count = 5, name = "Truesilver Transformer" },
        { item = 16000, count = 2, name = "Thorium Tube" },
    } },
}

C.ITEMS = {
    [765] = { name = "Silverleaf", stack = 20 },
    [783] = { name = "Light Hide", stack = 20 },
    [785] = { name = "Mageroyal", stack = 20 },
    [2318] = { name = "Light Leather", stack = 20 },
    [2319] = { name = "Medium Leather", stack = 20 },
    [2447] = { name = "Peacebloom", stack = 20 },
    [2449] = { name = "Earthroot", stack = 20 },
    [2450] = { name = "Briarthorn", stack = 20 },
    [2453] = { name = "Bruiseweed", stack = 20 },
    [2589] = { name = "Linen Cloth", stack = 20 },
    [2592] = { name = "Wool Cloth", stack = 20 },
    [2770] = { name = "Copper Ore", stack = 20 },
    [2771] = { name = "Tin Ore", stack = 20 },
    [2772] = { name = "Iron Ore", stack = 20 },
    [2775] = { name = "Silver Ore", stack = 20 },
    [2776] = { name = "Gold Ore", stack = 20 },
    [2840] = { name = "Copper Bar", stack = 20 },
    [2841] = { name = "Bronze Bar", stack = 20 },
    [2842] = { name = "Silver Bar", stack = 20 },
    [2880] = { name = "Weak Flux", stack = 10, vendor = 100, per = 1 },
    [2934] = { name = "Ruined Leather Scraps", stack = 20 },
    [2996] = { name = "Bolt of Linen Cloth", stack = 20 },
    [2997] = { name = "Bolt of Woolen Cloth", stack = 20 },
    [3355] = { name = "Wild Steelbloom", stack = 20 },
    [3356] = { name = "Kingsblood", stack = 20 },
    [3357] = { name = "Liferoot", stack = 20 },
    [3358] = { name = "Khadgar's Whisker", stack = 20 },
    [3369] = { name = "Grave Moss", stack = 20 },
    [3575] = { name = "Iron Bar", stack = 20 },
    [3576] = { name = "Tin Bar", stack = 20 },
    [3577] = { name = "Gold Bar", stack = 20 },
    [3818] = { name = "Fadeleaf", stack = 20 },
    [3819] = { name = "Wintersbite", stack = 20 },
    [3820] = { name = "Stranglekelp", stack = 20 },
    [3821] = { name = "Goldthorn", stack = 20 },
    [3857] = { name = "Coal", stack = 20, vendor = 500, per = 1 },
    [3858] = { name = "Mithril Ore", stack = 20 },
    [3859] = { name = "Steel Bar", stack = 20 },
    [3860] = { name = "Mithril Bar", stack = 20 },
    [4231] = { name = "Cured Light Hide", stack = 20 },
    [4232] = { name = "Medium Hide", stack = 20 },
    [4233] = { name = "Cured Medium Hide", stack = 20 },
    [4234] = { name = "Heavy Leather", stack = 20 },
    [4235] = { name = "Heavy Hide", stack = 20 },
    [4236] = { name = "Cured Heavy Hide", stack = 20 },
    [4289] = { name = "Salt", stack = 20, vendor = 50, per = 1 },
    [4304] = { name = "Thick Leather", stack = 20 },
    [4305] = { name = "Bolt of Silk Cloth", stack = 20 },
    [4306] = { name = "Silk Cloth", stack = 20 },
    [4338] = { name = "Mageweave Cloth", stack = 20 },
    [4339] = { name = "Bolt of Mageweave", stack = 20 },
    [4359] = { name = "Handful of Copper Bolts", stack = 20 },
    [4361] = { name = "Copper Tube", stack = 20 },
    [4363] = { name = "Copper Modulator", stack = 20 },
    [4371] = { name = "Bronze Tube", stack = 20 },
    [4375] = { name = "Whirring Bronze Gizmo", stack = 20 },
    [4382] = { name = "Bronze Framework", stack = 20 },
    [4387] = { name = "Iron Strut", stack = 20 },
    [4625] = { name = "Firebloom", stack = 20 },
    [6037] = { name = "Truesilver Bar", stack = 20 },
    [7067] = { name = "Elemental Earth", stack = 20 },
    [7069] = { name = "Elemental Air", stack = 20 },
    [7911] = { name = "Truesilver Ore", stack = 20 },
    [7912] = { name = "Solid Stone", stack = 20 },
    [8150] = { name = "Deeprock Salt", stack = 20 },
    [8169] = { name = "Thick Hide", stack = 20 },
    [8170] = { name = "Rugged Leather", stack = 20 },
    [8172] = { name = "Cured Thick Hide", stack = 20 },
    [8831] = { name = "Purple Lotus", stack = 20 },
    [8836] = { name = "Arthas' Tears", stack = 20 },
    [8838] = { name = "Sungrass", stack = 20 },
    [8839] = { name = "Blindweed", stack = 20 },
    [8845] = { name = "Ghost Mushroom", stack = 20 },
    [8846] = { name = "Gromsblood", stack = 20 },
    [10505] = { name = "Solid Blasting Powder", stack = 20 },
    [10558] = { name = "Gold Power Core", stack = 20 },
    [10559] = { name = "Mithril Tube", stack = 20 },
    [10560] = { name = "Unstable Trigger", stack = 20 },
    [10561] = { name = "Mithril Casing", stack = 20 },
    [10620] = { name = "Thorium Ore", stack = 20 },
    [10939] = { name = "Greater Magic Essence", stack = 20 },
    [10940] = { name = "Strange Dust", stack = 20 },
    [10978] = { name = "Small Glimmering Shard", stack = 20 },
    [11082] = { name = "Greater Astral Essence", stack = 20 },
    [11083] = { name = "Soul Dust", stack = 20 },
    [11084] = { name = "Large Glimmering Shard", stack = 20 },
    [11135] = { name = "Greater Mystic Essence", stack = 20 },
    [11137] = { name = "Vision Dust", stack = 20 },
    [11138] = { name = "Small Glowing Shard", stack = 20 },
    [11139] = { name = "Large Glowing Shard", stack = 20 },
    [11175] = { name = "Greater Nether Essence", stack = 20 },
    [11176] = { name = "Dream Dust", stack = 20 },
    [11177] = { name = "Small Radiant Shard", stack = 20 },
    [11178] = { name = "Large Radiant Shard", stack = 20 },
    [11370] = { name = "Dark Iron Ore", stack = 20 },
    [11371] = { name = "Dark Iron Bar", stack = 20 },
    [12359] = { name = "Thorium Bar", stack = 20 },
    [13463] = { name = "Dreamfoil", stack = 20 },
    [13464] = { name = "Golden Sansam", stack = 20 },
    [13465] = { name = "Mountain Silversage", stack = 20 },
    [13466] = { name = "Plaguebloom", stack = 20 },
    [13467] = { name = "Icecap", stack = 20 },
    [14047] = { name = "Runecloth", stack = 20 },
    [14048] = { name = "Bolt of Runecloth", stack = 20 },
    [14343] = { name = "Small Brilliant Shard", stack = 20 },
    [14344] = { name = "Large Brilliant Shard", stack = 20 },
    [15994] = { name = "Thorium Widget", stack = 20 },
    [16000] = { name = "Thorium Tube", stack = 20 },
    [18631] = { name = "Truesilver Transformer", stack = 20 },
}

C.RECIPES = {
    [2657] = { out = 2840, n = 1, prof = "Mining", name = "Smelt Copper", reagents = {
      { item = 2770, count = 1 },
    } },
    [2658] = { out = 2842, n = 1, prof = "Mining", name = "Smelt Silver", reagents = {
      { item = 2775, count = 1 },
    } },
    [2659] = { out = 2841, n = 2, prof = "Mining", name = "Smelt Bronze", reagents = {
      { item = 2840, count = 1 }, { item = 3576, count = 1 },
    } },
    [2881] = { out = 2318, n = 1, prof = "Leatherworking", name = "Light Leather", reagents = {
      { item = 2934, count = 3 },
    } },
    [2963] = { out = 2996, n = 1, prof = "Tailoring", name = "Bolt of Linen Cloth", reagents = {
      { item = 2589, count = 2 },
    } },
    [2964] = { out = 2997, n = 1, prof = "Tailoring", name = "Bolt of Woolen Cloth", reagents = {
      { item = 2592, count = 3 },
    } },
    [3304] = { out = 3576, n = 1, prof = "Mining", name = "Smelt Tin", reagents = {
      { item = 2771, count = 1 },
    } },
    [3307] = { out = 3575, n = 1, prof = "Mining", name = "Smelt Iron", reagents = {
      { item = 2772, count = 1 },
    } },
    [3308] = { out = 3577, n = 1, prof = "Mining", name = "Smelt Gold", reagents = {
      { item = 2776, count = 1 },
    } },
    [3569] = { out = 3859, n = 1, prof = "Mining", name = "Smelt Steel", reagents = {
      { item = 3575, count = 1 }, { item = 3857, count = 1 },
    } },
    [3816] = { out = 4231, n = 1, prof = "Leatherworking", name = "Cured Light Hide", reagents = {
      { item = 783, count = 1 }, { item = 4289, count = 1 },
    } },
    [3817] = { out = 4233, n = 1, prof = "Leatherworking", name = "Cured Medium Hide", reagents = {
      { item = 4232, count = 1 }, { item = 4289, count = 1 },
    } },
    [3818] = { out = 4236, n = 1, prof = "Leatherworking", name = "Cured Heavy Hide", reagents = {
      { item = 4235, count = 1 }, { item = 4289, count = 3 },
    } },
    [3839] = { out = 4305, n = 1, prof = "Tailoring", name = "Bolt of Silk Cloth", reagents = {
      { item = 4306, count = 4 },
    } },
    [3865] = { out = 4339, n = 1, prof = "Tailoring", name = "Bolt of Mageweave", reagents = {
      { item = 4338, count = 5 },
    } },
    [3922] = { out = 4359, n = 1, prof = "Engineering", name = "Handful of Copper Bolts", reagents = {
      { item = 2840, count = 1 },
    } },
    [3924] = { out = 4361, n = 1, prof = "Engineering", name = "Copper Tube", reagents = {
      { item = 2840, count = 2 }, { item = 2880, count = 1 },
    } },
    [3926] = { out = 4363, n = 1, prof = "Engineering", name = "Copper Modulator", reagents = {
      { item = 4359, count = 2 }, { item = 2840, count = 1 }, { item = 2589, count = 2 },
    } },
    [3938] = { out = 4371, n = 1, prof = "Engineering", name = "Bronze Tube", reagents = {
      { item = 2841, count = 2 }, { item = 2880, count = 1 },
    } },
    [3942] = { out = 4375, n = 1, prof = "Engineering", name = "Whirring Bronze Gizmo", reagents = {
      { item = 2841, count = 2 }, { item = 2592, count = 1 },
    } },
    [3953] = { out = 4382, n = 1, prof = "Engineering", name = "Bronze Framework", reagents = {
      { item = 2841, count = 2 }, { item = 2319, count = 1 }, { item = 2592, count = 1 },
    } },
    [3958] = { out = 4387, n = 1, prof = "Engineering", name = "Iron Strut", reagents = {
      { item = 3575, count = 2 },
    } },
    [10097] = { out = 3860, n = 1, prof = "Mining", name = "Smelt Mithril", reagents = {
      { item = 3858, count = 1 },
    } },
    [10098] = { out = 6037, n = 1, prof = "Mining", name = "Smelt Truesilver", reagents = {
      { item = 7911, count = 1 },
    } },
    [10482] = { out = 8172, n = 1, prof = "Leatherworking", name = "Cured Thick Hide", reagents = {
      { item = 8169, count = 1 }, { item = 8150, count = 1 },
    } },
    [11479] = { out = 3577, n = 1, prof = "Alchemy", name = "Transmute: Iron to Gold", reagents = {
      { item = 3575, count = 1 },
    } },
    [11480] = { out = 6037, n = 1, prof = "Alchemy", name = "Transmute: Mithril to Truesilver", reagents = {
      { item = 3860, count = 1 },
    } },
    [12584] = { out = 10558, n = 3, prof = "Engineering", name = "Gold Power Core", reagents = {
      { item = 3577, count = 1 },
    } },
    [12585] = { out = 10505, n = 1, prof = "Engineering", name = "Solid Blasting Powder", reagents = {
      { item = 7912, count = 2 },
    } },
    [12589] = { out = 10559, n = 1, prof = "Engineering", name = "Mithril Tube", reagents = {
      { item = 3860, count = 3 },
    } },
    [12591] = { out = 10560, n = 1, prof = "Engineering", name = "Unstable Trigger", reagents = {
      { item = 3860, count = 1 }, { item = 4338, count = 1 }, { item = 10505, count = 1 },
    } },
    [12599] = { out = 10561, n = 1, prof = "Engineering", name = "Mithril Casing", reagents = {
      { item = 3860, count = 3 },
    } },
    [14891] = { out = 11371, n = 1, prof = "Mining", name = "Smelt Dark Iron", reagents = {
      { item = 11370, count = 8 },
    } },
    [16153] = { out = 12359, n = 1, prof = "Mining", name = "Smelt Thorium", reagents = {
      { item = 10620, count = 1 },
    } },
    [18401] = { out = 14048, n = 1, prof = "Tailoring", name = "Bolt of Runecloth", reagents = {
      { item = 14047, count = 5 },
    } },
    [19791] = { out = 15994, n = 1, prof = "Engineering", name = "Thorium Widget", reagents = {
      { item = 12359, count = 3 }, { item = 14047, count = 1 },
    } },
    [19795] = { out = 16000, n = 1, prof = "Engineering", name = "Thorium Tube", reagents = {
      { item = 12359, count = 6 },
    } },
    [20648] = { out = 2319, n = 1, prof = "Leatherworking", name = "Medium Leather", reagents = {
      { item = 2318, count = 4 },
    } },
    [20649] = { out = 4234, n = 1, prof = "Leatherworking", name = "Heavy Leather", reagents = {
      { item = 2319, count = 5 },
    } },
    [20650] = { out = 4304, n = 1, prof = "Leatherworking", name = "Thick Leather", reagents = {
      { item = 4234, count = 6 },
    } },
    [22331] = { out = 8170, n = 1, prof = "Leatherworking", name = "Rugged Leather", reagents = {
      { item = 4304, count = 6 },
    } },
    [23071] = { out = 18631, n = 1, prof = "Engineering", name = "Truesilver Transformer", reagents = {
      { item = 6037, count = 2 }, { item = 7067, count = 2 }, { item = 7069, count = 1 },
    } },
}

C.ById, C.ByOutput = {}, {}
for _, crate in ipairs(C.LIST) do
    C.ById[crate.id] = crate
end
for spell, recipe in pairs(C.RECIPES) do
    local list = C.ByOutput[recipe.out] or {}
    list[#list + 1] = spell
    C.ByOutput[recipe.out] = list
end
for _, list in pairs(C.ByOutput) do
    table.sort(list)
end
