"""Regenerate AltArmy_TBC/Data/Economy/WaylaidCrates.lua: WoW Forever's Waylaid Crates and their bundles.

Usage: python scripts/generate-waylaid-crates.py [--db <website sqlite>] [--out <lua file>] [--check]

Reads the game data the website imports from the client's DB2 tables (the `items` table,
game_version 'forever'). Each shipment crate's Use text lists the bundles that fill it, any one of
them ("Fill the crate with any bundle from the following list: - 20 Peacebloom - 20 Silverleaf ...");
bundle names are resolved to item ids here so the addon needs no item lookups. The reagent trees under the
bundle items (every craft recipe making them or anything they take, with vendor prices and bonding) come
from the same database through generate-writs.py's `read_game` and `trees`, so the addon can price filling a
crate by crafting its bundle as it does a writ's order. Stdlib only.
The monorepo's game_data.py runs this daily against a fresh ingest of the pinned build (the game-data
workflow), and the site's local `ingest` runs it when it loads Forever data into its SQLite file.

--check writes nothing: it exits 1 when --out differs from what the game data gives (the pre-commit hook,
.githooks/pre-commit), and 0 with a note when the database isn't there to check against.
"""
import argparse
import importlib.util
import json
import os
import re
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DEFAULT_DB = os.path.join(ROOT, "..", "site", "data", "altarmy.sqlite")
DEFAULT_OUT = os.path.join(ROOT, "AltArmy_TBC", "Data", "Economy", "WaylaidCrates.lua")

GENERIC = 248549  # "Waylaid Crate": read its label to learn which shipment it is
FIRST, LAST = 248682, 248713  # the shipments ("Waylaid Crate: Apprentice Herbs", ...)
TIERS = ("Apprentice", "Journeyman", "Expert", "Artisan")
KIND_BY_QUALITY = {1: "Gathered", 2: "Crafted"}  # white crates take raw goods, green crates crafted ones
# Names that match more than one unbound item. Dark Iron Ore 11099 is a stack-of-10 quest variant.
OVERRIDES = {"Dark Iron Ore": 11370}
BUNDLE_LINE = re.compile(r"^- (\d+) (.+?)(?:\|r)?\s*$")
RECIPE_BAND = (30, 150)  # craft recipes the bundles' trees should reach: a broken ingest fails loudly


def load_writs_generator():
    """generate-writs.py (its `read_game`, `trees` and `render_trees`), loaded by its path."""
    spec = importlib.util.spec_from_file_location("generate_writs", os.path.join(HERE, "generate-writs.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def use_text(effects_json):
    for effect in json.loads(effects_json or "[]"):
        if effect.get("trigger") == "Use":
            return effect.get("text") or ""
    return ""


def resolve(db, name):
    if name in OVERRIDES:
        return OVERRIDES[name]
    rows = db.execute(
        "SELECT id FROM items WHERE game_version='forever' AND name=? AND bonding=0", (name,)
    ).fetchall()
    if len(rows) != 1:
        sys.exit(f"bundle item {name!r} matches {len(rows)} tradeable items; add it to OVERRIDES")
    return rows[0][0]


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(db_path):
    """The Lua module's text, from the website's database at `db_path`."""
    db = sqlite3.connect(f"file:{os.path.abspath(db_path)}?mode=ro", uri=True)
    rows = db.execute(
        "SELECT id, name, quality, effects FROM items WHERE game_version='forever'"
        " AND (id BETWEEN ? AND ? OR id=?) AND name LIKE 'Waylaid Crate%' ORDER BY id",
        (FIRST, LAST, GENERIC),
    ).fetchall()
    if len(rows) != 31:
        sys.exit(f"expected 31 Waylaid Crates, found {len(rows)}")

    out = [
        "-- AltArmy TBC — WoW Forever's Waylaid Crates and the bundles that fill them (Economy tab).",
        "-- GENERATED by scripts/generate-waylaid-crates.py from the client's game data: do not edit by hand.",
        "-- A shipment takes any ONE of its bundles. `kind`: Gathered (raw goods) or Crafted (crafted goods).",
        "-- The unread \"Waylaid Crate\" (GENERIC) becomes a random shipment when its label is read.",
        "-- ITEMS: every item the bundles' crafting trees touch (`vendor` copper per `per` units where a vendor",
        "-- sells it; `bop` binds on pickup). RECIPES: the craft recipes by spell id (`out`, `n` made per cast,",
        "-- `prof`, `reagents`), as in Writs.lua.",
        "",
        "if not AltArmy then return end",
        "",
        "AltArmy.WaylaidCrates = AltArmy.WaylaidCrates or {}",
        "local C = AltArmy.WaylaidCrates",
        "",
        f"C.GENERIC = {GENERIC}",
        "C.TIERS = { " + ", ".join(lua_str(t) for t in TIERS) + " }",
        "C.LIST = {",
    ]
    roots = []
    for item_id, name, quality, effects in rows:
        if item_id == GENERIC:
            out.append(
                f"    {{ id = {item_id}, name = {lua_str(name)}, short = {lua_str(name + ' (unread)')},"
                " random = true, bundles = {} },"
            )
            continue
        tier = next((t for t in TIERS if t in name), None)
        kind = KIND_BY_QUALITY.get(quality)
        if not tier or not kind:
            sys.exit(f"{item_id} {name!r}: no tier or kind")
        bundles = []
        for line in use_text(effects).replace("|cnIQ1:", "\n").splitlines():
            m = BUNDLE_LINE.match(line.strip())
            if m:
                count, bname = int(m.group(1)), m.group(2).strip()
                bundles.append((resolve(db, bname), count, bname))
                roots.append(bundles[-1][0])
        if len(bundles) < 2:
            sys.exit(f"{item_id} {name!r}: found {len(bundles)} bundles")
        short = name.split(": ", 1)[1]
        out.append(
            f"    {{ id = {item_id}, name = {lua_str(name)}, short = {lua_str(short)},"
        )
        out.append(f"      tier = {lua_str(tier)}, kind = {lua_str(kind)}, bundles = {{")
        for bid, count, bname in bundles:
            out.append(f"        {{ item = {bid}, count = {count}, name = {lua_str(bname)} }},")
        out.append("    } },")
    db.close()
    writs = load_writs_generator()
    _, items, vendor, recipes = writs.read_game(db_path)
    out_items, out_recipes = writs.trees(roots, items, vendor, recipes)
    if not RECIPE_BAND[0] <= len(out_recipes) <= RECIPE_BAND[1]:
        sys.exit(f"the bundles' trees reach {len(out_recipes)} recipes, expected {RECIPE_BAND[0]}-{RECIPE_BAND[1]}")
    out += ["}", ""]
    out += writs.render_trees("C", out_items, out_recipes)
    out += [
        "",
        "C.ById, C.ByOutput = {}, {}",
        "for _, crate in ipairs(C.LIST) do",
        "    C.ById[crate.id] = crate",
        "end",
        "for spell, recipe in pairs(C.RECIPES) do",
        "    local list = C.ByOutput[recipe.out] or {}",
        "    list[#list + 1] = spell",
        "    C.ByOutput[recipe.out] = list",
        "end",
        "for _, list in pairs(C.ByOutput) do",
        "    table.sort(list)",
        "end",
        "",
    ]
    return "\n".join(out), len(rows)


def read_normalized(path):
    """The file's text with LF line endings (git may check it out with CRLF), or None if it's missing."""
    try:
        with open(path, encoding="utf-8") as f:
            return f.read().replace("\r\n", "\n")
    except FileNotFoundError:
        return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="exit 1 if --out is out of date; write nothing")
    args = ap.parse_args()
    if args.check and not os.path.isfile(args.db):
        print(f"Waylaid Crates check skipped: no Alt Army website database at {os.path.abspath(args.db)}")
        return
    text, count = build(args.db)
    if args.check:
        if read_normalized(args.out) != text:
            sys.exit(
                f"{os.path.relpath(args.out)} is out of date with the website's game data.\n"
                "Run `python scripts/generate-waylaid-crates.py` and commit the change."
            )
        return
    if read_normalized(args.out) == text:
        print(f"{args.out}: already up to date ({count} crates)")
        return
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {args.out}: {count} crates")


if __name__ == "__main__":
    main()
